export TITLE="Bulwark Masternode"
export URL="https://github.com/bulwark-crypto/Bulwark/releases/download/2.2.0/bulwark-node-2.2.0.0-linux64.tar.gz"
export CHAINURL="https://chainseeder.masterhash.us/bwkchain.tar.gz"
export DAEMONCOMMAND="bulwarkd"
export CLICOMMAND="bulwark-cli"
export FILES="blocks database chainstate peers.dat"
export COINDIR=".bulwark"
export CONFFILE="bulwark.conf"