export TITLE="Deviant Masternode"
export URL="https://github.com/Deviantcoin/Source/releases/download/4.0.0.0/deviant-4.0.0-x86_64-linux-gnu.tar.gz"
export CHAINURL="https://chainseeder.masterhash.us/deviantchain.tar.gz"
export DAEMONCOMMAND="deviantd"
export CLICOMMAND="deviant-cli"
export FILES="blocks database chainstate peers.dat"
export COINDIR=".DeviantCore"
export CONFFILE="deviant.conf"