export TITLE="Magnet Masternode"
export URL="https://github.com/magnetwork/mag/releases/download/v1.0.0/mag-1.0.0-x86_64-linux-gnu.tar.gz"
export CHAINURL="https://chainseeder.masterhash.us/ginchain.tar.gz"
export DAEMONCOMMAND="magd"
export CLICOMMAND="mag-cli"
export FILES="blocks database chainstate peers.dat"
export COINDIR=".mag"
export CONFFILE="mag.conf"