export NAME="Pac Coin Masternode"
export URL="https://github.com/PACCommunity/PAC/releases/download/v0.12.6.1/PAC-v0.12.6.1-linux-x86_64.tar.gz"
export CHAINURL="https://chainseeder.masterhash.us/pacchain.tar.gz"
export DAEMONCOMMAND="paccoind"
export CLICOMMAND="paccoin-cli"
export FILES="blocks database chainstate peers.dat"
export COINDIR=".paccoincore"
export CONFFILE="paccoin.conf"