export NAME="Phore"
export URL="https://github.com/phoreproject/Phore/releases/download/v1.6.3/phore-1.6.3-x86_64-linux-gnu.tar.gz"
export CHAINURL="https://chainseeder.masterhash.us/phorechain.tar.gz"
export DAEMONCOMMAND="phored"
export CLICOMMAND="phore-cli"
export FILES="blocks database chainstate peers.dat"
export COINDIR=".phore"
export CONFFILE="phore.conf"