export NAME="SwiftCash Masternode"
export URL="https://github.com/swiftcashproject/swiftcash/releases/download/v2.0.1/swiftcash-2.0.1-x86_64-linux-gnu.tar.gz"
export CHAINURL="https://chainseeder.masterhash.us/swiftcashchain.tar.gz"
export DAEMONCOMMAND="swiftcashd"
export CLICOMMAND="swiftcash-cli"
export FILES="blocks database chainstate peers.dat"
export COINDIR=".swiftcash"
export CONFFILE="swiftnode.conf"