export NAME="Vulcano Masternode"
export URL="https://github.com/VulcanoCrypto/Vulcano/releases/download/2.1.0.0/Vulcano-2.1.0.0-x86_64-linux64-gnu.tar.gz"
export CHAINURL="https://chainseeder.masterhash.us/vulcchain.tar.gz"
export DAEMONCOMMAND="vulcanod"
export CLICOMMAND="vulcano-cli"
export FILES="blocks database chainstate peers.dat"
export COINDIR=".vulcanocore"
export CONFFILE="vulcano.conf"