export NAME="ZCoin"
export URL="https://github.com/zcoinofficial/zcoin/releases/download/v0.13.7.7/zcoin-0.13.7.7-linux64.tar.gz"
export CHAINURL="https://chainseeder.masterhash.us/zcoinchain.tar.gz"
export DAEMONCOMMAND="zcoind"
export CLICOMMAND="zcoin-cli"
export FILES="blocks database chainstate peers.dat"
export COINDIR=".zcoin"
export CONFFILE="zcoin.conf"
